/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root';
import { Route as CalendarRouteImport } from './pages/calendar';
import { Route as IndexRouteImport } from './pages/index';
import { Route as IntegrationsRouteImport } from './pages/integrations';
import { Route as IntegrationsGoogleRouteImport } from './pages/integrations.google';
import { Route as NotesRouteImport } from './pages/notes';
import { Route as RemindersRouteImport } from './pages/reminders';
import { Route as SettingsRouteImport } from './pages/settings';
import { Route as TasksRouteImport } from './pages/tasks';

const TasksRoute = TasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => rootRouteImport,
} as any);
const RemindersRoute = RemindersRouteImport.update({
    id: '/reminders',
    path: '/reminders',
    getParentRoute: () => rootRouteImport,
} as any);
const NotesRoute = NotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => rootRouteImport,
} as any);
const IntegrationsRoute = IntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => rootRouteImport,
} as any);
const CalendarRoute = CalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
} as any);
const IntegrationsGoogleRoute = IntegrationsGoogleRouteImport.update({
    id: '/google',
    path: '/google',
    getParentRoute: () => IntegrationsRoute,
} as any);

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute;
    '/calendar': typeof CalendarRoute;
    '/integrations': typeof IntegrationsRouteWithChildren;
    '/notes': typeof NotesRoute;
    '/reminders': typeof RemindersRoute;
    '/settings': typeof SettingsRoute;
    '/tasks': typeof TasksRoute;
    '/integrations/google': typeof IntegrationsGoogleRoute;
}
export interface FileRoutesByTo {
    '/': typeof IndexRoute;
    '/calendar': typeof CalendarRoute;
    '/integrations': typeof IntegrationsRouteWithChildren;
    '/notes': typeof NotesRoute;
    '/reminders': typeof RemindersRoute;
    '/settings': typeof SettingsRoute;
    '/tasks': typeof TasksRoute;
    '/integrations/google': typeof IntegrationsGoogleRoute;
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport;
    '/': typeof IndexRoute;
    '/calendar': typeof CalendarRoute;
    '/integrations': typeof IntegrationsRouteWithChildren;
    '/notes': typeof NotesRoute;
    '/reminders': typeof RemindersRoute;
    '/settings': typeof SettingsRoute;
    '/tasks': typeof TasksRoute;
    '/integrations/google': typeof IntegrationsGoogleRoute;
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths:
        | '/'
        | '/calendar'
        | '/integrations'
        | '/notes'
        | '/reminders'
        | '/settings'
        | '/tasks'
        | '/integrations/google';
    fileRoutesByTo: FileRoutesByTo;
    to:
        | '/'
        | '/calendar'
        | '/integrations'
        | '/notes'
        | '/reminders'
        | '/settings'
        | '/tasks'
        | '/integrations/google';
    id:
        | '__root__'
        | '/'
        | '/calendar'
        | '/integrations'
        | '/notes'
        | '/reminders'
        | '/settings'
        | '/tasks'
        | '/integrations/google';
    fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    CalendarRoute: typeof CalendarRoute;
    IntegrationsRoute: typeof IntegrationsRouteWithChildren;
    NotesRoute: typeof NotesRoute;
    RemindersRoute: typeof RemindersRoute;
    SettingsRoute: typeof SettingsRoute;
    TasksRoute: typeof TasksRoute;
}

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/tasks': {
            id: '/tasks';
            path: '/tasks';
            fullPath: '/tasks';
            preLoaderRoute: typeof TasksRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/settings': {
            id: '/settings';
            path: '/settings';
            fullPath: '/settings';
            preLoaderRoute: typeof SettingsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/reminders': {
            id: '/reminders';
            path: '/reminders';
            fullPath: '/reminders';
            preLoaderRoute: typeof RemindersRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/notes': {
            id: '/notes';
            path: '/notes';
            fullPath: '/notes';
            preLoaderRoute: typeof NotesRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/integrations': {
            id: '/integrations';
            path: '/integrations';
            fullPath: '/integrations';
            preLoaderRoute: typeof IntegrationsRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/calendar': {
            id: '/calendar';
            path: '/calendar';
            fullPath: '/calendar';
            preLoaderRoute: typeof CalendarRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/': {
            id: '/';
            path: '/';
            fullPath: '/';
            preLoaderRoute: typeof IndexRouteImport;
            parentRoute: typeof rootRouteImport;
        };
        '/integrations/google': {
            id: '/integrations/google';
            path: '/google';
            fullPath: '/integrations/google';
            preLoaderRoute: typeof IntegrationsGoogleRouteImport;
            parentRoute: typeof IntegrationsRoute;
        };
    }
}

interface IntegrationsRouteChildren {
    IntegrationsGoogleRoute: typeof IntegrationsGoogleRoute;
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
    IntegrationsGoogleRoute: IntegrationsGoogleRoute,
};

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(IntegrationsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    CalendarRoute: CalendarRoute,
    IntegrationsRoute: IntegrationsRouteWithChildren,
    NotesRoute: NotesRoute,
    RemindersRoute: RemindersRoute,
    SettingsRoute: SettingsRoute,
    TasksRoute: TasksRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();
